apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app: tamagotchi
configMapGenerator:
  - name: tamagotchi-config
    envs:
      - config/tamagotchi.env
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
